In [14]:
import numpy as np
np.__version__

'2.5.1'

In [15]:
# Scalar - a single number, 0 dimensions
scalar = np.array(5)

# Vector - a 1D array of numbers
vector = np.array([1, 2, 3])

# Matrix - a 2D array of numbers
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("Scalar:", scalar, "| shape:", scalar.shape, "| ndim:", scalar.ndim)
print("Vector:", vector, "| shape:", vector.shape, "| ndim:", vector.ndim)
print("Matrix:\n", matrix, "\n| shape:", matrix.shape, "| ndim:", matrix.ndim)

Scalar: 5 | shape: () | ndim: 0
Vector: [1 2 3] | shape: (3,) | ndim: 1
Matrix:
 [[1 2 3]
 [4 5 6]] 
| shape: (2, 3) | ndim: 2


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations (same shape, position-by-position)
print("Element-wise add:", a + b)
print("Element-wise multiply:", a * b)

# Dot product (used constantly in neural nets)
print("Dot product:", np.dot(a, b))

# Matrix multiplication with a matrix
W = np.array([[1, 0, 1],
              [0, 1, 1]])
print("Matrix @ vector:", W @ a)

# Transpose
print("Transpose of W:\n", W.T)

Element-wise add: [5 7 9]
Element-wise multiply: [ 4 10 18]
Dot product: 32
Matrix @ vector: [4 5]
Transpose of W:
 [[1 0]
 [0 1]
 [1 1]]


In [17]:
print("zeros:", np.zeros(3))
print("ones:", np.ones(3))
print("identity matrix:\n", np.eye(3))

# random weights, small values, mean 0
np.random.seed(42)  # so results are reproducible
random_weights = np.random.randn(2, 3)
print("random weights:\n", random_weights)

x = np.array([2.0, 5.0, 1.0])
print("argmax (index of biggest value):", np.argmax(x))
print("sum:", np.sum(x))
print("mean:", np.mean(x))
print("exp:", np.exp(x))

zeros: [0. 0. 0.]
ones: [1. 1. 1.]
identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random weights:
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]
argmax (index of biggest value): 1
sum: 8.0
mean: 2.6666666666666665
exp: [  7.3890561  148.4131591    2.71828183]


In [18]:
sequence = [1, 2, 3, 1, 2, 3, 1, 2, 3]

# Step 4: build input -> target pairs
inputs = sequence[:-1]
targets = sequence[1:]
print("Inputs: ", inputs)
print("Targets:", targets)

# Vocabulary
vocab = sorted(set(sequence))
vocab_size = len(vocab)
num_to_idx = {num: idx for idx, num in enumerate(vocab)}
idx_to_num = {idx: num for idx, num in enumerate(vocab)}
print("Vocab:", vocab, "| size:", vocab_size)
print("num_to_idx:", num_to_idx)

# Step 5: one-hot encoding function
def one_hot(num, vocab_size, num_to_idx):
    vec = np.zeros(vocab_size)
    vec[num_to_idx[num]] = 1
    return vec

# Test it
print("One-hot for 2:", one_hot(2, vocab_size, num_to_idx))

Inputs:  [1, 2, 3, 1, 2, 3, 1, 2]
Targets: [2, 3, 1, 2, 3, 1, 2, 3]
Vocab: [1, 2, 3] | size: 3
num_to_idx: {1: 0, 2: 1, 3: 2}
One-hot for 2: [0. 1. 0.]


In [19]:
hidden_size = 4
vocab_size = 3  # already defined earlier, just confirming

np.random.seed(42)

Wxh = np.random.randn(hidden_size, vocab_size) * 0.01
Whh = np.random.randn(hidden_size, hidden_size) * 0.01
bh = np.zeros(hidden_size)

h_prev = np.zeros(hidden_size)  # h_0, the very first hidden state

print("Wxh shape:", Wxh.shape)
print("Whh shape:", Whh.shape)
print("bh shape:", bh.shape)
print("h_prev (h0):", h_prev)

Wxh shape: (4, 3)
Whh shape: (4, 4)
bh shape: (4,)
h_prev (h0): [0. 0. 0. 0.]


In [20]:
# Take the very first input in our sequence: the number 1
x_t = one_hot(1, vocab_size, num_to_idx)
print("x_t (one-hot for input '1'):", x_t)

# The equation: h_t = tanh(Wxh @ x_t + Whh @ h_prev + bh)
a_t = Wxh @ x_t + Whh @ h_prev + bh
print("a_t (before tanh):", a_t)

h_t = np.tanh(a_t)
print("h_t (after tanh):", h_t)

x_t (one-hot for input '1'): [1. 0. 0.]
a_t (before tanh): [0.00496714 0.0152303  0.01579213 0.0054256 ]
h_t (after tanh): [0.0049671  0.01522912 0.01579082 0.00542555]


In [21]:
output_size = vocab_size  # we predict one of {1,2,3}, so output size = 3

np.random.seed(42)
Why = np.random.randn(output_size, hidden_size) * 0.01
by = np.zeros(output_size)

print("Why shape:", Why.shape)
print("by shape:", by.shape)

# The equation: o_t = Why @ h_t + by
o_t = Why @ h_t + by
print("o_t (raw output scores):", o_t)

Why shape: (3, 4)
by shape: (3,)
o_t (raw output scores): [ 1.88523860e-04  2.43720481e-04 -3.91379599e-05]


In [22]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

probs = softmax(o_t)
print("Probabilities:", probs)
print("Sum of probabilities:", np.sum(probs))

Probabilities: [0.33335249 0.33337089 0.33327661]
Sum of probabilities: 1.0


In [23]:
predicted_idx = np.argmax(probs)
predicted_num = idx_to_num[predicted_idx]

print("Predicted index:", predicted_idx)
print("Predicted number:", predicted_num)

Predicted index: 1
Predicted number: 2


In [24]:
# Our input was 1, and the correct target (from our dataset) is 2
target_num = 2
target_idx = num_to_idx[target_num]

p_correct = probs[target_idx]
loss = -np.log(p_correct)

print("Target index:", target_idx)
print("Probability assigned to correct answer:", p_correct)
print("Loss:", loss)

Target index: 1
Probability assigned to correct answer: 0.3333708946251238
Loss: 1.0984996111410892


In [25]:
h_prev = np.zeros(hidden_size)  # reset hidden state to h0 before starting the sequence

hidden_states = []
outputs = []
probs_list = []
losses = []

for t in range(len(inputs)):
    x_t = one_hot(inputs[t], vocab_size, num_to_idx)
    target_idx = num_to_idx[targets[t]]

    # Forward pass, one timestep
    a_t = Wxh @ x_t + Whh @ h_prev + bh
    h_t = np.tanh(a_t)
    o_t = Why @ h_t + by
    p_t = softmax(o_t)
    loss_t = -np.log(p_t[target_idx])

    # Store everything (we'll need it for BPTT later)
    hidden_states.append(h_t)
    outputs.append(o_t)
    probs_list.append(p_t)
    losses.append(loss_t)

    # Carry hidden state forward to next timestep
    h_prev = h_t

    print(f"t={t} | input={inputs[t]} target={targets[t]} | predicted={idx_to_num[np.argmax(p_t)]} | loss={loss_t:.4f}")

total_loss = np.mean(losses)
print("\nTotal average loss:", total_loss)

t=0 | input=1 target=2 | predicted=2 | loss=1.0985
t=1 | input=2 target=3 | predicted=2 | loss=1.0986
t=2 | input=3 target=1 | predicted=3 | loss=1.0986
t=3 | input=1 target=2 | predicted=2 | loss=1.0985
t=4 | input=2 target=3 | predicted=2 | loss=1.0986
t=5 | input=3 target=1 | predicted=3 | loss=1.0986
t=6 | input=1 target=2 | predicted=2 | loss=1.0985
t=7 | input=2 target=3 | predicted=2 | loss=1.0986

Total average loss: 1.0985835938178963


In [26]:
t = len(inputs) - 1  # last timestep
x_t = one_hot(inputs[t], vocab_size, num_to_idx)
target_idx = num_to_idx[targets[t]]
h_t = hidden_states[t]
p_t = probs_list[t]

# One-hot target vector
y_true = np.zeros(vocab_size)
y_true[target_idx] = 1

# Output error
delta_o = p_t - y_true
print("p_t:", p_t)
print("y_true:", y_true)
print("delta_o:", delta_o)

# Gradients for output layer
dWhy = np.outer(delta_o, h_t)
dby = delta_o

print("\ndWhy shape:", dWhy.shape, "(should match Why shape:", Why.shape, ")")
print("dby shape:", dby.shape)

p_t: [0.33331815 0.33335963 0.33332222]
y_true: [0. 0. 1.]
delta_o: [ 0.33331815  0.33335963 -0.66667778]

dWhy shape: (3, 4) (should match Why shape: (3, 4) )
dby shape: (3,)


In [27]:
h_prev_t = hidden_states[t-1] if t > 0 else np.zeros(hidden_size)

# Step A + B: hidden error, accounting for tanh derivative
delta_h = (Why.T @ delta_o) * (1 - h_t**2)
print("delta_h:", delta_h)

# Step C: gradients for hidden-layer parameters
dWxh = np.outer(delta_h, x_t)
dWhh = np.outer(delta_h, h_prev_t)
dbh = delta_h

print("\ndWxh shape:", dWxh.shape, "(should match Wxh:", Wxh.shape, ")")
print("dWhh shape:", dWhh.shape, "(should match Whh:", Whh.shape, ")")
print("dbh shape:", dbh.shape)

delta_h: [ 0.00400493 -0.00485847  0.01051221  0.01073952]

dWxh shape: (4, 3) (should match Wxh: (4, 3) )
dWhh shape: (4, 4) (should match Whh: (4, 4) )
dbh shape: (4,)


In [28]:
# Initialize gradient accumulators at zero
dWxh = np.zeros_like(Wxh)
dWhh = np.zeros_like(Whh)
dbh = np.zeros_like(bh)
dWhy = np.zeros_like(Why)
dby = np.zeros_like(by)

delta_h_next = np.zeros(hidden_size)  # no future error after the last timestep

for t in reversed(range(len(inputs))):
    x_t = one_hot(inputs[t], vocab_size, num_to_idx)
    target_idx = num_to_idx[targets[t]]
    h_t = hidden_states[t]
    h_prev_t = hidden_states[t-1] if t > 0 else np.zeros(hidden_size)
    p_t = probs_list[t]

    y_true = np.zeros(vocab_size)
    y_true[target_idx] = 1

    # Output error (Step 14)
    delta_o = p_t - y_true
    dWhy += np.outer(delta_o, h_t)
    dby += delta_o

    # Hidden error: own contribution + future contribution (Step 16 key equation)
    delta_h = (Why.T @ delta_o + Whh.T @ delta_h_next) * (1 - h_t**2)

    dWxh += np.outer(delta_h, x_t)
    dWhh += np.outer(delta_h, h_prev_t)
    dbh += delta_h

    delta_h_next = delta_h  # carry backward to the next (earlier) iteration

print("dWxh:\n", dWxh)
print("\ndWhh:\n", dWhh)
print("\ndbh:", dbh)
print("\ndWhy:\n", dWhy)
print("\ndby:", dby)

dWxh:
 [[ 0.00542318  0.01202703 -0.01163802]
 [ 0.00841088 -0.01435772  0.00389015]
 [-0.03015688  0.03190974 -0.00128672]
 [-0.00497158  0.03217931 -0.01812136]]

dWhh:
 [[ 1.07157251e-04  2.04888656e-04  8.54437986e-05  1.03991684e-04]
 [-4.45923084e-05 -2.42062349e-04 -2.24586743e-04 -1.23245609e-04]
 [ 3.55765720e-05  5.36907680e-04  5.90883024e-04  2.74877803e-04]
 [ 1.77798865e-04  5.45070062e-04  3.88461759e-04  2.77413701e-04]]

dbh: [ 0.00581218 -0.00205669  0.00046614  0.00908637]

dWhy:
 [[-0.00544318  0.01579687  0.02974042  0.00695796]
 [-0.00784611 -0.03462602 -0.02724596 -0.01882592]
 [ 0.0132893   0.01882915 -0.00249446  0.01186796]]

dby: [ 0.66667563 -0.33317923 -0.3334964 ]


In [29]:
predicted_idx = np.argmax(probs)
predicted_num = idx_to_num[predicted_idx]

print("Predicted index:", predicted_idx)
print("Predicted number:", predicted_num)

Predicted index: 1
Predicted number: 2


In [30]:
print("Clipped dWxh max/min:", dWxh.max(), dWxh.min())

Clipped dWxh max/min: 0.03217931382611953 -0.03015687587179549


In [31]:
learning_rate = 0.1

Wxh -= learning_rate * dWxh
Whh -= learning_rate * dWhh
bh  -= learning_rate * dbh
Why -= learning_rate * dWhy
by  -= learning_rate * dby

print("Updated Wxh:\n", Wxh)

Updated Wxh:
 [[ 0.00442482 -0.00258535  0.00764069]
 [ 0.01438921 -0.00090576 -0.00273038]
 [ 0.01880782  0.00448337 -0.00456607]
 [ 0.00592276 -0.00785211 -0.00284516]]


In [32]:
import numpy as np

# ============================================
# PHASE 2 — Dataset
# ============================================
sequence = [1, 2, 3, 1, 2, 3, 1, 2, 3]
inputs = sequence[:-1]
targets = sequence[1:]

vocab = sorted(set(sequence))
vocab_size = len(vocab)
num_to_idx = {num: idx for idx, num in enumerate(vocab)}
idx_to_num = {idx: num for idx, num in enumerate(vocab)}

def one_hot(num, vocab_size, num_to_idx):
    vec = np.zeros(vocab_size)
    vec[num_to_idx[num]] = 1
    return vec

# ============================================
# HELPER FUNCTIONS
# ============================================
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def clip_gradients(grads, clip_value=5):
    return [np.clip(g, -clip_value, clip_value) for g in grads]

# ============================================
# PHASE 3 — Initialize Parameters
# ============================================
np.random.seed(42)
hidden_size = 4
learning_rate = 0.1
epochs = 2000

Wxh = np.random.randn(hidden_size, vocab_size) * 0.01
Whh = np.random.randn(hidden_size, hidden_size) * 0.01
Why = np.random.randn(vocab_size, hidden_size) * 0.01
bh = np.zeros(hidden_size)
by = np.zeros(vocab_size)

# ============================================
# PHASE 9 — Training Loop
# ============================================
loss_history = []

for epoch in range(epochs):
    h_prev = np.zeros(hidden_size)
    hidden_states = []
    probs_list = []
    losses = []

    # ---- FORWARD PASS ----
    for t in range(len(inputs)):
        x_t = one_hot(inputs[t], vocab_size, num_to_idx)
        target_idx = num_to_idx[targets[t]]

        a_t = Wxh @ x_t + Whh @ h_prev + bh
        h_t = np.tanh(a_t)
        o_t = Why @ h_t + by
        p_t = softmax(o_t)
        loss_t = -np.log(p_t[target_idx])

        hidden_states.append(h_t)
        probs_list.append(p_t)
        losses.append(loss_t)
        h_prev = h_t

    total_loss = np.mean(losses)
    loss_history.append(total_loss)

    # ---- BACKWARD PASS (BPTT) ----
    dWxh = np.zeros_like(Wxh)
    dWhh = np.zeros_like(Whh)
    dbh = np.zeros_like(bh)
    dWhy = np.zeros_like(Why)
    dby = np.zeros_like(by)
    delta_h_next = np.zeros(hidden_size)

    for t in reversed(range(len(inputs))):
        x_t = one_hot(inputs[t], vocab_size, num_to_idx)
        target_idx = num_to_idx[targets[t]]
        h_t = hidden_states[t]
        h_prev_t = hidden_states[t-1] if t > 0 else np.zeros(hidden_size)
        p_t = probs_list[t]

        y_true = np.zeros(vocab_size)
        y_true[target_idx] = 1

        delta_o = p_t - y_true
        dWhy += np.outer(delta_o, h_t)
        dby += delta_o

        delta_h = (Why.T @ delta_o + Whh.T @ delta_h_next) * (1 - h_t**2)
        dWxh += np.outer(delta_h, x_t)
        dWhh += np.outer(delta_h, h_prev_t)
        dbh += delta_h

        delta_h_next = delta_h

    # ---- CLIP ----
    dWxh, dWhh, dbh, dWhy, dby = clip_gradients([dWxh, dWhh, dbh, dWhy, dby])

    # ---- UPDATE ----
    Wxh -= learning_rate * dWxh
    Whh -= learning_rate * dWhh
    bh  -= learning_rate * dbh
    Why -= learning_rate * dWhy
    by  -= learning_rate * dby

    if epoch % 200 == 0:
        print(f"Epoch {epoch:4d} | Loss: {total_loss:.4f}")

print(f"\nFinal Loss: {loss_history[-1]:.4f}")

# ============================================
# PHASE 10 — Test the Trained Model
# ============================================
print("\n--- Testing the trained RNN ---")
h_prev = np.zeros(hidden_size)

for test_input in [1, 2, 3]:
    x_t = one_hot(test_input, vocab_size, num_to_idx)
    a_t = Wxh @ x_t + Whh @ h_prev + bh
    h_t = np.tanh(a_t)
    o_t = Why @ h_t + by
    p_t = softmax(o_t)
    predicted_num = idx_to_num[np.argmax(p_t)]

    print(f"Input: {test_input} -> Predicted: {predicted_num} | Probabilities: {p_t}")
    h_prev = h_t

Epoch    0 | Loss: 1.0986
Epoch  200 | Loss: 0.0030
Epoch  400 | Loss: 0.0014
Epoch  600 | Loss: 0.0009
Epoch  800 | Loss: 0.0007
Epoch 1000 | Loss: 0.0005
Epoch 1200 | Loss: 0.0004
Epoch 1400 | Loss: 0.0004
Epoch 1600 | Loss: 0.0003
Epoch 1800 | Loss: 0.0003

Final Loss: 0.0003

--- Testing the trained RNN ---
Input: 1 -> Predicted: 2 | Probabilities: [2.78333454e-04 9.99584546e-01 1.37120733e-04]
Input: 2 -> Predicted: 3 | Probabilities: [1.02021398e-04 1.08551559e-04 9.99789427e-01]
Input: 3 -> Predicted: 1 | Probabilities: [9.99643508e-01 2.51293042e-04 1.05198639e-04]


In [33]:
print("\n==============================")
print("PHASE 11 — Sequence Generation")
print("==============================")

start_num = 1          # Starting number
steps = 10             # How many numbers to generate

generated = [start_num]

h_prev = np.zeros(hidden_size)
current_num = start_num

for _ in range(steps):

    # Convert current number to one-hot
    x_t = one_hot(current_num, vocab_size, num_to_idx)

    # Forward pass
    a_t = Wxh @ x_t + Whh @ h_prev + bh
    h_t = np.tanh(a_t)

    o_t = Why @ h_t + by
    p_t = softmax(o_t)

    # Predict next number
    predicted_idx = np.argmax(p_t)
    predicted_num = idx_to_num[predicted_idx]

    generated.append(predicted_num)

    # Feed prediction back as next input
    current_num = predicted_num
    h_prev = h_t

print("Generated sequence:")
print(generated)


PHASE 11 — Sequence Generation
Generated sequence:
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2]


In [34]:
def predict(num):

    if num not in [1, 2, 3]:
        print("Invalid input!")
        return

    h_prev = np.zeros(hidden_size)

    x_t = one_hot(num, vocab_size, num_to_idx)

    a_t = Wxh @ x_t + Whh @ h_prev + bh
    h_t = np.tanh(a_t)

    o_t = Why @ h_t + by
    p_t = softmax(o_t)

    predicted_idx = np.argmax(p_t)
    predicted_num = idx_to_num[predicted_idx]

    print(f"Input: {num}")
    print(f"Prediction: {predicted_num}")
    print(f"Probabilities: {p_t}")

In [35]:
predict(1)
print()

predict(2)
print()

predict(3)

Input: 1
Prediction: 2
Probabilities: [2.78333454e-04 9.99584546e-01 1.37120733e-04]

Input: 2
Prediction: 3
Probabilities: [0.00552386 0.0038101  0.99066604]

Input: 3
Prediction: 1
Probabilities: [0.96240817 0.01797545 0.01961638]


In [36]:
import numpy as np

In [37]:
predict(1)
predict(2)
predict(3)

Input: 1
Prediction: 2
Probabilities: [2.78333454e-04 9.99584546e-01 1.37120733e-04]
Input: 2
Prediction: 3
Probabilities: [0.00552386 0.0038101  0.99066604]
Input: 3
Prediction: 1
Probabilities: [0.96240817 0.01797545 0.01961638]
